<Project>

  <Target Name="GetGitBranch" BeforeTargets="BeforeBuild">
    <Message Text="Calculating Git branch..." />
    <Exec Command="git rev-parse --show-toplevel" WorkingDirectory="$(MSBuildProjectDirectory)" ConsoleToMSBuild="true">
      <Output TaskParameter="ConsoleOutput" PropertyName="GitRootDirectory"/>
    </Exec>
  </Target>

  <Target Name="GetGitRoot" BeforeTargets="BeforeBuild">
    <Message Text="Calculating Git root directory..." />
    <Exec Command="git rev-parse --symbolic-full-name @{upstream}" WorkingDirectory="$(MSBuildProjectDirectory)" ConsoleToMSBuild="true">
      <Output TaskParameter="ConsoleOutput" PropertyName="GitBranch"/>
    </Exec>
  </Target>

  <Target Name="CheckPackageProjectUrl" BeforeTargets="BeforeBuild">
    <Error Text="PackageProjectUrl property is not set" Condition=" '$(PackageProjectUrl)' == '' " />
  </Target>

  <ItemGroup>
    <CompilerVisibleProperty Include="GitRootDirectory;GitBranch;PackageProjectUrl" />
  </ItemGroup>

</Project>